### ISSUE TITLE
support of file chunk and resume

### ISSUE THREAD

**Issue by martingg88** [danielgtaylor/node-desktop-uploader#1]
does it support of sending file in chunk and can i resume post the file to server in case for any internet interruption?

**Comment by danielgtaylor** [comment]
@martingg88 it does not support chunked multipart uploads (this requires special code on the server to concatenate the parts into the final file). In the case of Internet interruption the file will be retried until all retries are exhausted, then it will fail. You can try to detect network interruption and pause the uploader from your code, or listen for error events and track the files which didn't upload that way. Hope this helps!

**Comment by martingg88** [comment]
thanks.

**Comment by danielgtaylor** [comment]
No problem. Let me know if you need anything else!
